apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    server {
      listen 80;
      location / {
        proxy_pass https://yandex.ru;
      }    
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-conf-test

spec:
  selector:
    matchLabels:
      app: nginx-conf-test
  replicas: 1
  type: RollingUpdate

  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-conf-test
    spec:
      containers:
      - name: nginx-test
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        resources:
          limits:
            cpu: 200m
            memory: 256M
      volumes:
      - name: nginx-config
        configMap:
          name: config-nginx
