replicaCount: 3
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"
podLabels: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
  # targetMemoryUtilizationPercentage: 80
  # nodeSelector:
  #   kubernetes.io/hostname: 'master-95.143.191.163'

tolerations: []

affinity: {}
