apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-echo-app
  labels:
    app: k8s-echo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-echo-app
  template:
    metadata:
      labels:
        app: k8s-echo-app
    spec:
      containers:
      - name: k8s-echo-app
        image: matvey5686/k8s-app:latest
        imagePullPolicy: Always
        ports:
        - name: k8s-app-port
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-echo-app-service
  labels:
    app: k8s-echo-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: k8s-echo-app
