apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-deployment
  labels:
    app: webpage-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webpage-app
  template:
    metadata:
      labels:
        app: webpage-app
    spec:
      containers:
      - name: webpage
        image: fabianogaspar/webpage
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: webpage-service
  labels:
    app: webpage-app
spec:
  type: ClusterIP
  selector:
    app: webpage-app
  ports:
  - port: 8000
    targetPort: http
    name: http
