apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: cat-dog

spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: cat-dog
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: cat-dog

    spec:
      containers:
      - name: postgres-container
        image: postgres
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
