apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    name: redis-deploy
    app: cat-dog

spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: cat-dog
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: cat-dog

    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1000Mi
