apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
    app: cat-dog

spec:
  replicas: 2
  selector:
    matchLabels:
      name: voting-app-pod
      app: cat-dog
  template:
    metadata:
      name: voting-app-pod
      labels:
        name: voting-app-pod
        app: cat-dog

    spec:
      containers:
      - name: voting-container
        image: kodekloud/examplevotingapp_vote:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
