apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    name: worker-deploy
    app: cat-dog

spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: cat-dog
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: cat-dog

    spec:
      containers:
      - name: worker-container
        image: kodekloud/examplevotingapp_worker:v1
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1Gi
