apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: cat-dog

spec:
  type: ClusterIP
  selector:
    name: postgres-pod
    app: cat-dog
  ports:
  - port: 5432
    targetPort: 5432
