apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: cat-dog

spec:
  type: ClusterIP
  selector:
    name: redis-pod
    app: cat-dog
  ports:
  - port: 6379
    targetPort: 6379
