apiVersion: v1
kind: Service
metadata:
  name: result-app-service
  labels:
    name: result-app-service
    app: cat-dog

spec:
  type: NodePort
  selector:
    name: result-app-pod
    app: cat-dog
  ports:
  - nodePort: 30005
    port: 80
    targetPort: 80
