apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app-service
    app: cat-dog

spec:
  type: NodePort
  selector:
    name: voting-app-pod
    app: cat-dog
  ports:
  - nodePort: 30004
    port: 80
    targetPort: 80
