apiVersion: apps/v1
kind: Deployment
metadata:
  name: wb-depl
  labels:
    app: wb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wb
  template:
    metadata:
      labels:
        app: wb
    spec:
      containers:
      - name: web-nginx
        image: nginx:latest
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: wb-svc
  labels:
    app: wb
spec:
  type: LoadBalancer
  selector:
    app: wb
  ports:
  - name: http
    port: 9080
    targetPort: http
    protocol: TCP
  - name: https
    port: 9443
    targetPort: https
    protocol: TCP
